var profile = {};
profile.name = 'surendra';
profile.code = 1234;
profile.prof = 1223443 + 'zwe3sr3rsrs';
profile.array = ['surendra', 'kumar'];
console.log('=====name====', profile.name);
console.log('====code====', profile.code);
console.log('====prof====', profile.prof);
console.log('====Array====', profile.array);
console.log(profile);
